# Manipulating/comparing arrays

In [6]:
import numpy as np

#### Arithmatic

In [7]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [5]:
ones = np.ones([4])
ones

array([1., 1., 1., 1.])

In [6]:
a1 + ones

array([2., 3., 4., 5.])

In [7]:
a1 - ones

array([0., 1., 2., 3.])

In [8]:
a1 * ones

array([1., 2., 3., 4.])

In [9]:
a1/ones

array([1., 2., 3., 4.])

In [10]:
ones/a1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [15]:
a2 = np.random.randint(1, 10, size=(2, 4))
a2

array([[2, 3, 8, 3],
       [9, 2, 4, 5]])

In [16]:
a1 * a2

array([[ 2,  6, 24, 12],
       [ 9,  4, 12, 20]])

In [21]:
a3 = np.random.randint(1, 50, size=(2,4))
a3

array([[10, 13,  2, 47],
       [44, 12,  9, 17]])

In [22]:
a2 * a3

array([[60, 78,  8, 47],
       [44, 24, 72, 51]])

In [23]:
a2 ** 2

array([[36, 36, 16,  1],
       [ 1,  4, 64,  9]])

In [24]:
np.square(a3)

array([[ 100,  169,    4, 2209],
       [1936,  144,   81,  289]])

In [25]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [26]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

#### Aggregation
It means to perform same operations on a no of things

In [2]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
sum(list1)

15

In [8]:
sum(a1)

10

In [9]:
np.sum(a1)

10

In [10]:
#use sum() method while working with python data types and np.sum() while working with numpy arrays

In [11]:
new_array = np.random.random(10000)
new_array

array([0.32907885, 0.82147511, 0.87846589, ..., 0.48841162, 0.27195919,
       0.73551788])

In [12]:
new_array.size

10000

In [13]:
new_array[:100]

array([0.32907885, 0.82147511, 0.87846589, 0.0532263 , 0.13595572,
       0.17842883, 0.35536964, 0.62655985, 0.932734  , 0.4926451 ,
       0.96587372, 0.05271926, 0.98762271, 0.1982382 , 0.87284599,
       0.39287948, 0.46182566, 0.89556488, 0.15419394, 0.26466855,
       0.36016236, 0.3591478 , 0.43756487, 0.62632979, 0.83103103,
       0.800412  , 0.58281174, 0.28387362, 0.19767932, 0.11726925,
       0.35416461, 0.23590517, 0.8073482 , 0.8972028 , 0.87618913,
       0.35388234, 0.79911785, 0.59711917, 0.19231437, 0.53531955,
       0.18116943, 0.11615219, 0.90428556, 0.38544618, 0.27428366,
       0.02586227, 0.78920846, 0.90867723, 0.42283138, 0.09208274,
       0.82130322, 0.73426309, 0.76628599, 0.80759673, 0.32020454,
       0.79019664, 0.40107105, 0.80399519, 0.45506802, 0.44464705,
       0.94347253, 0.07690645, 0.07608914, 0.60227436, 0.14218089,
       0.79530206, 0.7722443 , 0.0789866 , 0.51922383, 0.20886253,
       0.81328773, 0.17275933, 0.98263888, 0.47411715, 0.56209

In [14]:
%timeit sum(new_array) #python's sum()
%timeit np.sum(new_array) #numpy's sum [much faster]

1.69 ms ± 95 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
19.1 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
a2

array([[2, 3, 8, 3],
       [9, 2, 4, 5]])

In [18]:
np.sum(a2)

36

In [19]:
np.mean(a2)

4.5

In [20]:
np.max(a2)

9

In [21]:
#standard deviation
np.std(a2)

2.5

In [22]:
#variance
np.var(a2)

6.25

In [24]:
np.sqrt(np.var(a2))

2.5