In [1]:
import numpy as np

# Data Types and Attributes

In [2]:
#numpy's main data type is ndarray(n-dimensional array)
#shape(1,5)
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
#shape(2,3)
arr2 = np.array([[1,2,4.5],
                [3,4.4,6]])
arr2

array([[1. , 2. , 4.5],
       [3. , 4.4, 6. ]])

In [9]:
#shape(3,2,3)
arr3 = np.array([[[1,2,4],
                [5,6,3]],
                [[4,1,3],
                [6,5,4]],
                [[3,2,1],
                [7,6,7]]])
arr3

array([[[1, 2, 4],
        [5, 6, 3]],

       [[4, 1, 3],
        [6, 5, 4]],

       [[3, 2, 1],
        [7, 6, 7]]])

In [11]:
arr1.shape

(5,)

In [12]:
arr2.shape

(2, 3)

In [13]:
arr3.shape

(3, 2, 3)

In [14]:
#no of dimensions
arr1.ndim , arr2.ndim, arr3.ndim

(1, 2, 3)

In [15]:
#no of elements
arr1.size, arr2.size, arr3.size

(5, 6, 18)

In [18]:
#create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  4.5
1  3.0  4.4  6.0