# Comparison Operators

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,4.5],
              [3,7,6.5]])
a2

array([[1. , 2. , 4.5],
       [3. , 7. , 6.5]])

In [5]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [6]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

In [7]:
a1<5

array([ True,  True,  True])

In [8]:
a1 != a2

array([[False, False,  True],
       [ True,  True,  True]])