# Sorting arrays

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10, size=(3,5))
arr

array([[4, 3, 2, 3, 8],
       [5, 1, 2, 0, 5],
       [2, 8, 8, 7, 7]])

In [4]:
np.sort(arr)

array([[2, 3, 3, 4, 8],
       [0, 1, 2, 5, 5],
       [2, 7, 7, 8, 8]])

In [5]:
#Returns the indices that would sort an array
np.argsort(arr)

array([[2, 1, 3, 0, 4],
       [3, 1, 2, 0, 4],
       [0, 3, 4, 1, 2]], dtype=int64)

In [10]:
arr

array([[4, 3, 2, 3, 8],
       [5, 1, 2, 0, 5],
       [2, 8, 8, 7, 7]])

In [8]:
#considers cols
np.argmax(arr, axis=0)

array([1, 2, 2, 2, 0], dtype=int64)

In [9]:
#considers rows
np.argmax(arr, axis=1)

array([4, 0, 1], dtype=int64)