# Viewing arrays & matrices

In [1]:
import numpy as np

In [4]:
a1 = np.random.randint(0,10, size=(2,3))

In [5]:
a1

array([[4, 2, 2],
       [1, 6, 1]])

In [6]:
np.unique(a1)

array([1, 2, 4, 6])

In [8]:
a1[1]

array([1, 6, 1])

In [10]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2[0]

array([1, 2, 3])

In [12]:
a3 = np.array([1,2,5,6,4])
a3[3]

6

In [13]:
a2[:2,:2]

array([[1, 2],
       [4, 5]])

In [19]:
a4 = np.array([[[1,2,3],
              [4,5,6]],
              [[7,1,2],
              [4,5,1]],
              [[7,8,2],
              [3,3,1]]]) 
a4[:3,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[7, 1],
        [4, 5]],

       [[7, 8],
        [3, 3]]])

In [20]:
a4.shape

(3, 2, 3)

In [22]:
arr_random = np.random.randint(0, 20, size=(2, 4, 5))
arr_random

array([[[19,  7,  4,  2,  5],
        [ 4,  4, 13, 16,  7],
        [11,  1,  7,  4,  8],
        [15,  2, 18, 10,  4]],

       [[11,  7,  8, 13,  1],
        [14,  4, 19,  0, 15],
        [ 6,  9,  9,  7,  8],
        [17,  8,  1, 18, 13]]])

In [23]:
arr_random.shape

(2, 4, 5)

In [25]:
arr_random[:2, :2, :3]

array([[[19,  7,  4],
        [ 4,  4, 13]],

       [[11,  7,  8],
        [14,  4, 19]]])