# Reshaping & Transposing

In [50]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([[1,2,3],
               [4,6,8]])
arr

array([[1, 2, 3],
       [4, 6, 8]])

In [3]:
arr.shape

(2, 3)

In [4]:
arr1 = np.array([[[1,6,7],
                 [3,3,1]],
                 [[2,5,7],
                 [4,8,9]],
                 [[2,3,4],
                 [8,9,1]]])
arr1

array([[[1, 6, 7],
        [3, 3, 1]],

       [[2, 5, 7],
        [4, 8, 9]],

       [[2, 3, 4],
        [8, 9, 1]]])

In [6]:
arr1.shape

(3, 2, 3)

In [7]:
arr * arr1

array([[[ 1, 12, 21],
        [12, 18,  8]],

       [[ 2, 10, 21],
        [16, 48, 72]],

       [[ 2,  6, 12],
        [32, 54,  8]]])

In [22]:
arr2 = np.array([[[1,2,3],
                [6,4,2],
                [2,3,5]],
                [[1,3,5],
                [5,3,8],
                [3,6,4]]])
arr2

array([[[1, 2, 3],
        [6, 4, 2],
        [2, 3, 5]],

       [[1, 3, 5],
        [5, 3, 8],
        [3, 6, 4]]])

In [23]:
arr * arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [24]:
arr.shape

(2, 3)

In [25]:
arr_reshaped = arr.reshape(2,3,1)

In [26]:
arr_reshaped * arr2

array([[[ 1,  2,  3],
        [12,  8,  4],
        [ 6,  9, 15]],

       [[ 4, 12, 20],
        [30, 18, 48],
        [24, 48, 32]]])

In [27]:
arr2.shape

(2, 3, 3)

In [30]:
new = arr2.T
new

array([[[1, 1],
        [6, 5],
        [2, 3]],

       [[2, 3],
        [4, 3],
        [3, 6]],

       [[3, 5],
        [2, 8],
        [5, 4]]])

In [31]:
new.shape

(3, 3, 2)

# Dot Product

In [32]:
np.random.seed(0)
mat1 = np.random.randint(1, 20, size=(5,3))
mat2 = np.random.randint(1, 50, size=(5,3))

In [35]:
mat1

array([[13, 16,  1],
       [ 4,  4,  8],
       [10, 19,  5],
       [ 7, 13,  2],
       [ 7,  8, 15]])

In [34]:
mat2

array([[25, 18, 38],
       [26, 14,  9],
       [10, 21, 17],
       [ 6, 16, 48],
       [ 1, 19, 36]])

In [36]:
#Element-wise multiplication(Hadamard product)
mat1 * mat2

array([[325, 288,  38],
       [104,  56,  72],
       [100, 399,  85],
       [ 42, 208,  96],
       [  7, 152, 540]])

In [37]:
#Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [38]:
mat1.T

array([[13,  4, 10,  7,  7],
       [16,  4, 19, 13,  8],
       [ 1,  8,  5,  2, 15]])

In [40]:
mat1.T.shape

(3, 5)

In [41]:
mat2.shape

(5, 3)

In [45]:
np.dot(mat1.T, mat2)

array([[ 578,  745, 1288],
       [ 780, 1103, 1879],
       [ 310,  552,  831]])

In [42]:
mat2.T

array([[25, 26, 10,  6,  1],
       [18, 14, 21, 16, 19],
       [38,  9, 17, 48, 36]])

In [43]:
np.dot(mat2.T, mat1)

array([[ 578,  780,  310],
       [ 745, 1103,  552],
       [1288, 1879,  831]])

In [46]:
np.dot(mat1,mat2.T)

array([[651, 571, 483, 382, 353],
       [476, 232, 260, 472, 368],
       [782, 571, 584, 604, 551],
       [485, 382, 377, 346, 326],
       [889, 429, 493, 890, 699]])

# Dot Product Example

In [48]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [51]:
#creating weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [52]:
price = np.array([10,6,12])
price

array([10,  6, 12])

In [56]:
prices = pd.DataFrame(price.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
prices

Almond butter  Peanut butter  Cashew butter
Price             10              6             12

In [57]:
sales_amount.shape

(5, 3)

In [58]:
prices.shape

(1, 3)

In [59]:
total_sales = prices.dot(sales_amount.T)
total_sales

0    1    2    3    4
Price  210  132  420  220  130

In [60]:
#create daily sales
prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [61]:
weekly_sales.T

Mon  Tues  Wed  Thurs  Fri
Almond butter   12     3    9      4    1
Peanut butter   15     3   19      6    6
Cashew butter    0     7   18     12    7

In [62]:
daily_sales = prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  210   132  420    220  130

In [63]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [64]:
daily_sales.T

Price
Mon      210
Tues     132
Wed      420
Thurs    220
Fri      130

In [65]:
weekly_sales["Total($)"] = daily_sales.T

In [66]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total($)
Mon               12             15              0       210
Tues               3              3              7       132
Wed                9             19             18       420
Thurs              4              6             12       220
Fri                1              6              7       130