# Creating arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr.dtype

dtype('int32')

In [9]:
#returns array filled with ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
#return arrays with zeros
arr2 = np.zeros((4,5))

In [12]:
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#range array
arr3 = np.arange(0, 10, 3)
arr3

array([0, 3, 6, 9])

In [14]:
#return array with random values
arr4 = np.random.randint(0, 15, size=(2,4)) 

In [15]:
arr4

array([[ 0,  9,  2,  9],
       [14,  0, 13, 13]])

In [16]:
arr4.size

8

In [17]:
arr4.shape

(2, 4)

In [18]:
#returns random float values btw 0 to 1
arr5 = np.random.random((5,3))
arr5

array([[0.73491814, 0.57696447, 0.08250374],
       [0.17212758, 0.10176446, 0.47763533],
       [0.0075158 , 0.69494288, 0.8739502 ],
       [0.60495399, 0.30289822, 0.40785868],
       [0.15917231, 0.61304849, 0.83090556]])

In [24]:
#random seed() allows generate random no that are reproducible
np.random.seed(seed = 0) #seed = any no
arr6 = np.random.random((5,3))
arr6

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])